
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SARROW CONSTANT DOUBLEARROW HAT LPAREN NEGATION OR RPAREN VARIABLES : LPAREN S RPARENS : VARIABLES : CONSTANTS : NEGATION SS : S DOUBLEARROW SS : S ARROW SS : S HAT SS : S OR S'
    
_lr_action_items = {'LPAREN':([0,2,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'VARIABLE':([0,2,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'CONSTANT':([0,2,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'NEGATION':([0,2,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,3,4,11,12,13,14,15,16,],[0,-2,-3,-4,-5,-6,-7,-8,-1,]),'DOUBLEARROW':([1,3,4,10,11,12,13,14,15,16,],[6,-2,-3,6,6,6,6,6,6,-1,]),'ARROW':([1,3,4,10,11,12,13,14,15,16,],[7,-2,-3,7,7,7,7,7,7,-1,]),'HAT':([1,3,4,10,11,12,13,14,15,16,],[8,-2,-3,8,8,8,8,8,8,-1,]),'OR':([1,3,4,10,11,12,13,14,15,16,],[9,-2,-3,9,9,9,9,9,9,-1,]),'RPAREN':([3,4,10,11,12,13,14,15,16,],[-2,-3,16,-4,-5,-6,-7,-8,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,2,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> LPAREN S RPAREN','S',3,'p_parentheses','hello_lex.py',47),
  ('S -> VARIABLE','S',1,'p_VAR','hello_lex.py',51),
  ('S -> CONSTANT','S',1,'p_CONS','hello_lex.py',55),
  ('S -> NEGATION S','S',2,'p_NEG','hello_lex.py',59),
  ('S -> S DOUBLEARROW S','S',3,'p_DOUBLEARROW','hello_lex.py',63),
  ('S -> S ARROW S','S',3,'p_ARROW','hello_lex.py',67),
  ('S -> S HAT S','S',3,'p_HAT','hello_lex.py',71),
  ('S -> S OR S','S',3,'p_OR','hello_lex.py',75),
]
